spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ladushki
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ladushki-course-project-secret
